<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalmingReferenceSeeder extends Seeder
{
    public function run(): void
    {
        $notificationTemplates = [
            ['key' => 'article_saved', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'article', 'title' => 'Articol salvat', 'message' => 'Articolul a fost salvat în biblioteca ta personală.', 'default_title' => 'Articol salvat', 'default_body' => 'Articolul a fost salvat în biblioteca ta personală.', 'icon' => 'FiBookmark', 'icon_color' => 'lilac', 'accent' => 'lilac', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi notificările', 'deep_link' => '/notifications', 'sort_order' => 10, 'is_repeatable' => 0, 'is_active' => 1],
            ['key' => 'article_reminder_set', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'reminder', 'title' => 'Reminder pentru articol', 'message' => 'Ai activat un reminder pentru a reveni la articol.', 'default_title' => 'Reminder pentru articol', 'default_body' => 'Ai activat un reminder pentru a reveni la articol.', 'icon' => 'FiCalendar', 'icon_color' => 'rose', 'accent' => 'rose', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Deschide articolul', 'deep_link' => '/learn', 'sort_order' => 20, 'is_repeatable' => 0, 'is_active' => 1],
            ['key' => 'journal_saved', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'journal', 'title' => 'Intrare nouă în jurnal', 'message' => 'Am salvat reflecția ta și am actualizat progresul personal.', 'default_title' => 'Intrare nouă în jurnal', 'default_body' => 'Am salvat reflecția ta și am actualizat progresul personal.', 'icon' => 'FiHeart', 'icon_color' => 'mint', 'accent' => 'mint', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi jurnalul', 'deep_link' => '/journal', 'sort_order' => 30, 'is_repeatable' => 0, 'is_active' => 1],
            ['key' => 'quick_check_in_saved', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'journal', 'title' => 'Check-in salvat', 'message' => 'Am notat starea ta rapidă pentru azi.', 'default_title' => 'Check-in salvat', 'default_body' => 'Am notat starea ta rapidă pentru azi.', 'icon' => 'FiHeart', 'icon_color' => 'mint', 'accent' => 'mint', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi jurnalul', 'deep_link' => '/journal', 'sort_order' => 40, 'is_repeatable' => 0, 'is_active' => 1],
            ['key' => 'appointment_created', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'appointment', 'title' => 'Programare confirmată', 'message' => 'Programarea ta a fost salvată.', 'default_title' => 'Programare confirmată', 'default_body' => 'Programarea ta a fost salvată.', 'icon' => 'FiCalendar', 'icon_color' => 'peach', 'accent' => 'peach', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi programările', 'deep_link' => '/appointments', 'sort_order' => 50, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'appointment_reminder_24h', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'appointment', 'title' => 'Reminder programare', 'message' => 'Urmează programarea ta.', 'default_title' => 'Reminder programare', 'default_body' => 'Urmează programarea ta.', 'icon' => 'FiClock', 'icon_color' => 'peach', 'accent' => 'peach', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi agenda', 'deep_link' => '/appointments', 'sort_order' => 60, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'milestone_unlocked', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'milestone', 'title' => 'Reper nou deblocat', 'message' => 'Ai atins un nou reper în Calming.', 'default_title' => 'Reper nou deblocat', 'default_body' => 'Ai atins un nou reper în Calming.', 'icon' => 'FiAward', 'icon_color' => 'rose', 'accent' => 'rose', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi profilul', 'deep_link' => '/profile', 'sort_order' => 70, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'profile_completed', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'profile', 'title' => 'Profil complet', 'message' => 'Profilul tău este complet și poți primi recomandări mai bune.', 'default_title' => 'Profil complet', 'default_body' => 'Profilul tău este complet și poți primi recomandări mai bune.', 'icon' => 'FiUser', 'icon_color' => 'sky', 'accent' => 'sky', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi profilul', 'deep_link' => '/profile', 'sort_order' => 80, 'is_repeatable' => 0, 'is_active' => 1],
            ['key' => 'community_member_update', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'community', 'title' => 'Actualizare comunitate', 'message' => 'Există activitate nouă în comunitatea ta.', 'default_title' => 'Actualizare comunitate', 'default_body' => 'Există activitate nouă în comunitatea ta.', 'icon' => 'FiUsers', 'icon_color' => 'amber', 'accent' => 'amber', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi comunitatea', 'deep_link' => '/community', 'sort_order' => 90, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'community_public_update', 'audience' => 'general', 'actor_type' => 'both', 'category' => 'community', 'title' => 'Actualizare comunitate', 'message' => 'Activitate nouă într-un grup public Calming.', 'default_title' => 'Actualizare comunitate', 'default_body' => 'Activitate nouă într-un grup public Calming.', 'icon' => 'FiUsers', 'icon_color' => 'amber', 'accent' => 'amber', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Vezi comunitatea', 'deep_link' => '/community', 'sort_order' => 100, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'community_private_invite', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'community', 'title' => 'Invitație în grup privat', 'message' => 'Ai primit o invitație într-un grup privat din comunitatea Calming.', 'default_title' => 'Invitație în grup privat', 'default_body' => 'Ai primit o invitație într-un grup privat din comunitatea Calming.', 'icon' => 'FiUsers', 'icon_color' => 'indigo', 'accent' => 'indigo', 'priority' => 4, 'cta_kind' => 'open', 'cta_label' => 'Vezi grupul', 'deep_link' => '/community', 'sort_order' => 110, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'article_published', 'audience' => 'general', 'actor_type' => 'both', 'category' => 'article', 'title' => 'Articol nou', 'message' => 'A apărut un articol nou în biblioteca Calming.', 'default_title' => 'Articol nou', 'default_body' => 'A apărut un articol nou în biblioteca Calming.', 'icon' => 'FiBookOpen', 'icon_color' => 'lilac', 'accent' => 'lilac', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Citește acum', 'deep_link' => '/learn', 'sort_order' => 120, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'assistant_tip_ready', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'assistant', 'title' => 'AI Assistant', 'message' => 'Assistantul a pregătit un nou punct de pornire pentru tine.', 'default_title' => 'AI Assistant', 'default_body' => 'Assistantul a pregătit un nou punct de pornire pentru tine.', 'icon' => 'FiMessageSquare', 'icon_color' => 'sky', 'accent' => 'sky', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Deschide Assistant', 'deep_link' => '/assistant', 'sort_order' => 130, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'assistant_follow_up', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'assistant', 'title' => 'Follow-up Assistant', 'message' => 'Assistantul poate continua de unde ați rămas și îți poate propune următorul pas.', 'default_title' => 'Follow-up Assistant', 'default_body' => 'Assistantul poate continua de unde ați rămas și îți poate propune următorul pas.', 'icon' => 'FiMessageSquare', 'icon_color' => 'sky', 'accent' => 'sky', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Continuă conversația', 'deep_link' => '/assistant', 'sort_order' => 140, 'is_repeatable' => 1, 'is_active' => 1],
            ['key' => 'assistant_check_in_due', 'audience' => 'authenticated', 'actor_type' => 'user', 'category' => 'assistant', 'title' => 'Check-in cu Assistant', 'message' => 'Este un moment bun pentru un nou check-in, în intervalul tău preferat.', 'default_title' => 'Check-in cu Assistant', 'default_body' => 'Este un moment bun pentru un nou check-in, în intervalul tău preferat.', 'icon' => 'FiMessageSquare', 'icon_color' => 'sky', 'accent' => 'sky', 'priority' => 3, 'cta_kind' => 'open', 'cta_label' => 'Deschide Assistant', 'deep_link' => '/assistant', 'sort_order' => 150, 'is_repeatable' => 1, 'is_active' => 1],
        ];

        foreach ($notificationTemplates as $template) {
            DB::table('notification_templates')->updateOrInsert(
                ['key' => $template['key']],
                $template + ['published_at' => now()]
            );
        }
    }
}
